# Generated by Django 4.0.5 on 2022-06-21 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_alter_comment_post_alter_comment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePlaceSale',
            new_name='Restaurant',
        ),
    ]
